source "https://rubygems.org"
gem "fastlane"
gem "xcode-install"
gem 'fastlane-plugin-github_action', git: "https://github.com/joshdholtz/fastlane-plugin-github_action"
gem "cocoapods", "~> 1.16.2" 
gem "xcodeproj", "~> 1.27.0"