# чтобы не было ошибки "app_identifier пуст"
app_identifier ENV["IOS_BUNDLE_ID"]

submit_for_review false
automatic_release false
force true
skip_screenshots true
skip_metadata true
run_precheck_before_submit false
